p-182 navbar style
JTKsson/jolint-webbapp pull request #24
Opened 2023-10-26 19:55 UTC by CyberGalactus

review please. Should I make the navbar responsive now, or should I wait?

2023-10-27 09:07 UTC, JTKsson requested changes
you should make it responsive right away

2023-11-06 12:30 UTC, JTKsson requested changes
1. fixa rätt font till headern
2. bra hamburgermeny. Du behöver däremot kolla responsiviteten innan brytpunkten. 
Som det är just nu så lägger sig "consent form"-knappen sig under länkarna när skärmen blir för liten innan den hoppar till mobil-vy. 

Hör av dig om du vill att jag blir tydligare eller behöver hjälp

2023-11-08 14:29 UTC, JTKsson approved these changes

2023-11-09 08:54 UTC, milutxi approved these changes

2023-11-10 19:21 UTC, merged